name: Push Tag - Release CLI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag version to release'
        required: true

permissions:
  contents: write
  packages: write

env:
  CLI_NAME: ctnr
  CTNR_API_URL: https://api.ctnr.io

jobs:
  build-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            os: linux
            arch: x64
            ext: ""
          - target: aarch64-unknown-linux-gnu
            os: linux
            arch: arm64
            ext: ""
          - target: x86_64-apple-darwin
            os: darwin
            arch: x64
            ext: ""
          - target: aarch64-apple-darwin
            os: darwin
            arch: arm64
            ext: ""
          - target: x86_64-pc-windows-msvc
            os: windows
            arch: x64
            ext: ".exe"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: latest 

      - name: Get Version
        id: version
        run: |
          # If workflow is triggered by a tag, use the tag name
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "version=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "Tag version detected: ${{ github.ref_name }}"
          else
            # Ensure the tag with the version exists
            echo "Checking for tag with version ${{ github.event.inputs.version }}"
            if [[ -z "${{ github.event.inputs.version }}" ]]; then
              echo "No version input provided."
              exit 1
            else 
              echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
              echo "Using version from input: ${{ github.event.inputs.version }}"
            fi
          fi


      - name: Compile cli binary
        run: |
          mkdir -p dist
          
          # Set environment variables for compilation
          export CTNR_API_URL="${{ env.CTNR_API_URL }}"
          
          # Compile the CLI with embedded environment variables
          deno compile \
            --allow-all \
            --target ${{ matrix.target }} \
            --output dist/${{ env.CLI_NAME }}-cli-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }} \
            cli/main.ts
        env:
          CTNR_API_URL: ${{ env.CTNR_API_URL }}

      - name: Create tarball (Unix)
        if: matrix.os != 'windows'
        run: |
          cd dist
          tar -czf ${{ env.CLI_NAME }}-cli-${{ steps.version.outputs.version }}-${{ matrix.os }}-${{ matrix.arch }}.tar.gz ${{ env.CLI_NAME }}-cli-${{ matrix.os }}-${{ matrix.arch }}

      - name: Create zip (Windows)
        if: matrix.os == 'windows'
        run: |
          cd dist
          zip ${{ env.CLI_NAME }}-cli-${{ steps.version.outputs.version }}-${{ matrix.os }}-${{ matrix.arch }}.zip ${{ env.CLI_NAME }}-cli-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.CLI_NAME }}-cli-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            dist/${{ env.CLI_NAME }}-cli-${{ steps.version.outputs.version }}-${{ matrix.os }}-${{ matrix.arch }}.*

  release-cli:
    needs: build-cli
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Version
        id: version
        run: |
          # If workflow is triggered by a tag, use the tag name
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "version=${{ github.ref_name }}" >> $GITHUB_ENV
            echo "Tag version detected: ${{ github.ref_name }}"
          else
            # Ensure the tag with the version exists
            echo "Checking for tag with version ${{ github.event.inputs.version }}"
            if [[ -z "${{ github.event.inputs.version }}" ]]; then
              echo "No version input provided."
              exit 1
            else 
              echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
              echo "Using version from input: ${{ github.event.inputs.version }}"
            fi
          fi

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Prepare release assets
        run: |
          # Flatten the artifact structure
          find dist -name "*.tar.gz" -o -name "*.zip" | while read file; do
            mv "$file" ./
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            *.tar.gz
            *.zip
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
